all:
	gcc -I include -I cmd -I var_array main.c cmd/cmd.c var_array/var_array.c -o mosh -Wall -Werror
debug:
	gcc -I include -I cmd -I var_array main.c cmd/cmd.c var_array/var_array.c -o mosh -Wall -Werror -g
